In [1]:

# File:  convert_neiss_original_data_to_pckl_v7.ipynb

from code_id_translator import *
import numpy as np
import os
import pandas as pd
import pickle
import re

- If Neiss_data.pckl exists read it into the dataframe.  Otherwise, read all the neiss1999 ... neiss2018 files into a dataframe and save that dataframe as neiss_data.pckl

In [2]:
neiss_pathname = os.getcwd() + '/data/NEISS'

def readNeissPcklFile(pckl_fname):
    if os.path.exists(pckl_fname):
        print("Reading {}  ... ".format(pckl_fname), end="")
        neiss_df = pickle.load( open( pckl_fname, "rb" ) )
        print("done!")
        return neiss_df
    return None

def readNeissOriginalData(neiss_pathname, expression):
    neiss_df = pd.DataFrame()
    for subdir, dirs, files in os.walk(neiss_pathname):
        files.sort()
        filtered_fnames = filter(lambda fname: re.search(expression, fname), files)

        for index, file in enumerate(filtered_fnames):
            fname = '{}/{}'.format(subdir, file)
            print("Reading {}  ... ".format(fname))

            neiss_df1 = pd.read_excel(fname)
            neiss_df = pd.concat([neiss_df, neiss_df1])
    return neiss_df1

def saveNeissOriginalDataToPcklFile(df, pckl_fname):
    with open(pckl_fname, 'wb') as f:
        pickle.dump(df, f)
        print("Saved", pckl_fname)
        
pckl_fname_neiss = neiss_pathname + '/neiss_data.pckl'
neiss_df = readNeissPcklFile(pckl_fname_neiss)
if neiss_df.empty:
    neiss_df = readNeissOriginalData(neiss_pathname, '^neiss\d{4}.xlsx$')
    saveNeissOriginalDataToPcklFile(neiss_df, pckl_fname_neiss)
neiss_df

#

Reading /Users/mcorbett/Boston University/MET CS677 - Data Science with Python/Project/data/NEISS/neiss_data.pckl  ... done!

,CPSC_Case_Number,Treatment_Date,Age,Sex,Race,Other_Race,Body_Part,Diagnosis,Other_Diagnosis,Disposition,Location,Fire_Involvement,Product_1,Product_2,Narrative_1,Narrative_2,Stratum,PSU,Weight
0,180106119,2018-01-01,57,2,2,NaN,79,53,NaN,1,1,0,4074,611,57 YO F CAREGIVER WAS BATHING PT WHEN PT SLID ...,NaN,S,71,70.9703
1,180106122,2018-01-01,70,1,1,NaN,76,59,NaN,1,0,0,4057,0,70 YO M VOMITTING AND PASSED OUT HITTING HEAD ...,NaN,S,71,70.9703
2,180106156,2018-01-01,75,1,1,NaN,75,59,NaN,1,1,0,1807,0,75YOM-SCALP LAC-FELL HITTING HEAD ON CONCRETE ...,NaN,S,11,70.9703
3,180106157,2018-01-01,34,1,1,NaN,92,59,NaN,1,1,0,474,0,34YOM-FINGER LAC-CUT ON A BROKEN COFFEE MUG-@ ...,NaN,S,11,70.9703
4,180106178,2018-01-01,33,1,3,HISPANIC,92,59,NaN,1,1,0,464,0,33YOM WAS CUTTING LIMES WITH A KNIFE AND CUT L...,NaN,S,46,70.9703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361662,190404184,2018-12-23,65,2,0,NaN,92,59,NaN,1,1,0,464,0,65YOF CUT FINGER WITH KITCHEN KNIFE. DX: FINGE...,NaN,V,21,17.5136
361663,190404185,2018-12-23,9,1,0,NaN,80,57,NaN,4,1,0,4074,0,9YOM RUNNING WITH BEAN BAG CHAIR AND FELL ONTO...,NaN,V,21,17.5136
361664,190404186,2018-12-23,35,1,0,NaN,92,59,NaN,1,1,0,464,0,35YOM CUT FINGER WITH KITCHEN KNIFE. DX: FINGE...,NaN,V,21,17.5136
361665,190404188,2018-12-23,43,1,0,NaN,83,64,NaN,1,1,0,679,0,43YOM ROLLED FOOT WHEN GETTING UP FROM COUCH. ...,NaN,V,21,17.5136
361666,190404189,2018-12-23,47,2,0,NaN,92,59,NaN,1,1,0,478,0,47YOF CUT FINGER ON BROKEN DRINKING GLASS. DX:...,NaN,V,21,17.5136

In [3]:
categories =  [
    'Sex', 'Race', 'Body_Part', 'Diagnosis', 'Disposition', 'Location',
    'Fire_Involvement', 'Product_1', 'Product_2', 'PSU', 'Stratum']

test_df = neiss_df.copy()
codeIdTranslator = CodeIdTranslatorDataFrame(test_df, categories)
print(codeIdTranslator)

print('--------------------------------------------------------------------')

print('--- Before')
print(test_df['Body_Part'])
codeIdTranslator.transformColumn('Body_Part')
print('--- After transform ')
print(test_df['Body_Part'])
print('--- After inverseTransform ')
codeIdTranslator.inverseTransformColumn('Body_Part')
print(test_df['Body_Part'])

print('--------------------------------------------------------------------')

print('--- Before')
print(test_df)
codeIdTranslator.transformColumns()
print('--- After transform ')
print(test_df)
print('--- After inverseTransform ')
codeIdTranslator.inverseTransformColumns()
print(test_df)

print('--------------------------------------------------------------------')

                                                                  translator
Function Category
codeToId Body_Part         [{0: 1, 30: 2, 31: 3, 32: 4, 33: 5, 34: 6, 35:...
         Diagnosis         [{41: 1, 42: 2, 46: 3, 47: 4, 48: 5, 49: 6, 50...
         Disposition            [{1: 1, 2: 2, 4: 3, 5: 4, 6: 5, 8: 6, 9: 7}]
         Fire_Involvement                         [{0: 1, 1: 2, 2: 3, 3: 4}]
         Location          [{0: 1, 1: 2, 2: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8:...
         PSU               [{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8:...
         Product_1         [{102: 1, 106: 2, 107: 3, 110: 4, 112: 5, 113:...
         Product_2         [{0: 1, 106: 2, 110: 3, 112: 4, 113: 5, 115: 6...
         Race                   [{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7}]
         Sex                                            [{0: 1, 1: 2, 2: 3}]
         Stratum                  [{'C': 1, 'L': 2, 'M': 3, 'S': 4, 'V': 5}]
idToCode Body_Part         [{1: 0, 2: 30, 3: 31, 4: 32, 5: 33, 6: 34, 7: ...
         Diagnosis         [{1: 41, 2: 42, 3: 46, 4: 47, 5: 48, 6: 49, 7:...
         Disposition            [{1: 1, 2: 2, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9}]
         Fire_Involvement                         [{1: 0, 2: 1, 3: 2, 4: 3}]
         Location          [{1: 0, 2: 1, 3: 2, 4: 4, 5: 5, 6: 6, 7: 7, 8:...
         PSU               [{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8:...
         Product_1         [{1: 102, 2: 106, 3: 107, 4: 110, 5: 112, 6: 1...
         Product_2         [{1: 0, 2: 106, 3: 110, 4: 112, 5: 113, 6: 115...
         Race                   [{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6}]
         Sex                                            [{1: 0, 2: 1, 3: 2}]
         Stratum                  [{1: 'C', 2: 'L', 3: 'M', 4: 'S', 5: 'V'}]
--------------------------------------------------------------------
--- Before
0         79
1         76
2         75
3         92
4         92
          ..
361662    92
361663    80
361664    92
361665    83
361666    92
Name: Body_Part, Length: 361667, dtype: int64
--- After transform
0         14
1         12
2         11
3         24
4         24
          ..
361662    24
361663    15
361664    24
361665    18
361666    24
Name: Body_Part, Length: 361667, dtype: int64
--- After inverseTransform
0         79
1         76
2         75
3         92
4         92
          ..
361662    92
361663    80
361664    92
361665    83
361666    92
Name: Body_Part, Length: 361667, dtype: int64
--------------------------------------------------------------------
--- Before
        CPSC_Case_Number Treatment_Date  Age  Sex  Race Other_Race  Body_Part  \
0              180106119     2018-01-01   57    2     2        NaN         79
1              180106122     2018-01-01   70    1     1        NaN         76
2              180106156     2018-01-01   75    1     1        NaN         75
3              180106157     2018-01-01   34    1     1        NaN         92
4              180106178     2018-01-01   33    1     3   HISPANIC         92
...                  ...            ...  ...  ...   ...        ...        ...
361662         190404184     2018-12-23   65    2     0        NaN         92
361663         190404185     2018-12-23    9    1     0        NaN         80
361664         190404186     2018-12-23   35    1     0        NaN         92
361665         190404188     2018-12-23   43    1     0        NaN         83
361666         190404189     2018-12-23   47    2     0        NaN         92

        Diagnosis Other_Diagnosis  Disposition  Location  Fire_Involvement  \
0              53             NaN            1         1                 0
1              59             NaN            1         0                 0
2              59             NaN            1         1                 0
3              59             NaN            1         1                 0
4              59             NaN            1         1                 0
...           ...             ...          ...       ...               ...
361662         59             NaN            1         1                 0
361663         57             NaN            4         1                 0
361664         59             NaN            1         1                 0
361665         64             NaN            1         1                 0
361666         59             NaN            1         1                 0

        Product_1  Product_2  \
0            4074        611
1            4057          0
2            1807          0
3             474          0
4             464          0
...           ...        ...
361662        464          0
361663       4074          0
361664        464          0
361665        679          0
361666        478          0

                                              Narrative_1  Narrative_2  \
0       57 YO F CAREGIVER WAS BATHING PT WHEN PT SLID ...          NaN
1       70 YO M VOMITTING AND PASSED OUT HITTING HEAD ...          NaN
2       75YOM-SCALP LAC-FELL HITTING HEAD ON CONCRETE ...          NaN
3       34YOM-FINGER LAC-CUT ON A BROKEN COFFEE MUG-@ ...          NaN
4       33YOM WAS CUTTING LIMES WITH A KNIFE AND CUT L...          NaN
...                                                   ...          ...
361662  65YOF CUT FINGER WITH KITCHEN KNIFE. DX: FINGE...          NaN
361663  9YOM RUNNING WITH BEAN BAG CHAIR AND FELL ONTO...          NaN
361664  35YOM CUT FINGER WITH KITCHEN KNIFE. DX: FINGE...          NaN
361665  43YOM ROLLED FOOT WHEN GETTING UP FROM COUCH. ...          NaN
361666  47YOF CUT FINGER ON BROKEN DRINKING GLASS. DX:...          NaN

       Stratum  PSU   Weight
0            S   71  70.9703
1            S   71  70.9703
2            S   11  70.9703
3            S   11  70.9703
4            S   46  70.9703
...        ...  ...      ...
361662       V   21  17.5136
361663       V   21  17.5136
361664       V   21  17.5136
361665       V   21  17.5136
361666       V   21  17.5136

[361667 rows x 19 columns]
--- After transform
        CPSC_Case_Number Treatment_Date  Age  Sex  Race Other_Race  Body_Part  \
0              180106119     2018-01-01   57    3     3        NaN         14
1              180106122     2018-01-01   70    2     2        NaN         12
2              180106156     2018-01-01   75    2     2        NaN         11
3              180106157     2018-01-01   34    2     2        NaN         24
4              180106178     2018-01-01   33    2     4   HISPANIC         24
...                  ...            ...  ...  ...   ...        ...        ...
361662         190404184     2018-12-23   65    3     1        NaN         24
361663         190404185     2018-12-23    9    2     1        NaN         15
361664         190404186     2018-12-23   35    2     1        NaN         24
361665         190404188     2018-12-23   43    2     1        NaN         18
361666         190404189     2018-12-23   47    3     1        NaN         24

        Diagnosis Other_Diagnosis  Disposition  Location  Fire_Involvement  \
0              10             NaN            1         2                 1
1              16             NaN            1         1                 1
2              16             NaN            1         2                 1
3              16             NaN            1         2                 1
4              16             NaN            1         2                 1
...           ...             ...          ...       ...               ...
361662         16             NaN            1         2                 1
361663         14             NaN            3         2                 1
361664         16             NaN            1         2                 1
361665         21             NaN            1         2                 1
361666         16             NaN            1         2                 1

        Product_1  Product_2  \
0             719        137
1             706          1
2             573          1
3             122          1
4             117          1
...           ...        ...
361662        117          1
361663        719          1
361664        117          1
361665        188          1
361666        124          1

                                              Narrative_1  Narrative_2  \
0       57 YO F CAREGIVER WAS BATHING PT WHEN PT SLID ...          NaN
1       70 YO M VOMITTING AND PASSED OUT HITTING HEAD ...          NaN
2       75YOM-SCALP LAC-FELL HITTING HEAD ON CONCRETE ...          NaN
3       34YOM-FINGER LAC-CUT ON A BROKEN COFFEE MUG-@ ...          NaN
4       33YOM WAS CUTTING LIMES WITH A KNIFE AND CUT L...          NaN
...                                                   ...          ...
361662  65YOF CUT FINGER WITH KITCHEN KNIFE. DX: FINGE...          NaN
361663  9YOM RUNNING WITH BEAN BAG CHAIR AND FELL ONTO...          NaN
361664  35YOM CUT FINGER WITH KITCHEN KNIFE. DX: FINGE...          NaN
361665  43YOM ROLLED FOOT WHEN GETTING UP FROM COUCH. ...          NaN
361666  47YOF CUT FINGER ON BROKEN DRINKING GLASS. DX:...          NaN

        Stratum  PSU   Weight
0             4   61  70.9703
1             4   61  70.9703
2             4   11  70.9703
3             4   11  70.9703
4             4   42  70.9703
...         ...  ...      ...
361662        5   19  17.5136
361663        5   19  17.5136
361664        5   19  17.5136
361665        5   19  17.5136
361666        5   19  17.5136

[361667 rows x 19 columns]
--- After inverseTransform

        CPSC_Case_Number Treatment_Date  Age  Sex  Race Other_Race  Body_Part  \
0              180106119     2018-01-01   57    2     2        NaN         79
1              180106122     2018-01-01   70    1     1        NaN         76
2              180106156     2018-01-01   75    1     1        NaN         75
3              180106157     2018-01-01   34    1     1        NaN         92
4              180106178     2018-01-01   33    1     3   HISPANIC         92
...                  ...            ...  ...  ...   ...        ...        ...
361662         190404184     2018-12-23   65    2     0        NaN         92
361663         190404185     2018-12-23    9    1     0        NaN         80
361664         190404186     2018-12-23   35    1     0        NaN         92
361665         190404188     2018-12-23   43    1     0        NaN         83
361666         190404189     2018-12-23   47    2     0        NaN         92

        Diagnosis Other_Diagnosis  Disposition  Location  Fire_Involvement  \
0              53             NaN            1         1                 0
1              59             NaN            1         0                 0
2              59             NaN            1         1                 0
3              59             NaN            1         1                 0
4              59             NaN            1         1                 0
...           ...             ...          ...       ...               ...
361662         59             NaN            1         1                 0
361663         57             NaN            4         1                 0
361664         59             NaN            1         1                 0
361665         64             NaN            1         1                 0
361666         59             NaN            1         1                 0

        Product_1  Product_2  \
0            4074        611
1            4057          0
2            1807          0
3             474          0
4             464          0
...           ...        ...
361662        464          0
361663       4074          0
361664        464          0
361665        679          0
361666        478          0

                                              Narrative_1  Narrative_2  \
0       57 YO F CAREGIVER WAS BATHING PT WHEN PT SLID ...          NaN
1       70 YO M VOMITTING AND PASSED OUT HITTING HEAD ...          NaN
2       75YOM-SCALP LAC-FELL HITTING HEAD ON CONCRETE ...          NaN
3       34YOM-FINGER LAC-CUT ON A BROKEN COFFEE MUG-@ ...          NaN
4       33YOM WAS CUTTING LIMES WITH A KNIFE AND CUT L...          NaN
...                                                   ...          ...
361662  65YOF CUT FINGER WITH KITCHEN KNIFE. DX: FINGE...          NaN
361663  9YOM RUNNING WITH BEAN BAG CHAIR AND FELL ONTO...          NaN
361664  35YOM CUT FINGER WITH KITCHEN KNIFE. DX: FINGE...          NaN
361665  43YOM ROLLED FOOT WHEN GETTING UP FROM COUCH. ...          NaN
361666  47YOF CUT FINGER ON BROKEN DRINKING GLASS. DX:...          NaN

       Stratum  PSU   Weight
0            S   71  70.9703
1            S   71  70.9703
2            S   11  70.9703
3            S   11  70.9703
4            S   46  70.9703
...        ...  ...      ...
361662       V   21  17.5136
361663       V   21  17.5136
361664       V   21  17.5136
361665       V   21  17.5136
361666       V   21  17.5136

[361667 rows x 19 columns]
--------------------------------------------------------------------